// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXB-N0pwK44OHO7QFg0mvpNoiUnN98FGA',
    appId: '1:937627284243:web:301b5b42ec0a5b16f260e6',
    messagingSenderId: '937627284243',
    projectId: 'studio-ghibli-filmes-zduuwn',
    authDomain: 'studio-ghibli-filmes-zduuwn.firebaseapp.com',
    databaseURL: 'https://studio-ghibli-filmes-zduuwn-default-rtdb.firebaseio.com',
    storageBucket: 'studio-ghibli-filmes-zduuwn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgpr8i4MSAA6SXqnW28cTkSey0e7AxooE',
    appId: '1:937627284243:android:34dfa125339c8f50f260e6',
    messagingSenderId: '937627284243',
    projectId: 'studio-ghibli-filmes-zduuwn',
    databaseURL: 'https://studio-ghibli-filmes-zduuwn-default-rtdb.firebaseio.com',
    storageBucket: 'studio-ghibli-filmes-zduuwn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNM938NYNJT99COnM2TlTNeD2P3ymoZw',
    appId: '1:937627284243:ios:5f0d53a5f4200ec1f260e6',
    messagingSenderId: '937627284243',
    projectId: 'studio-ghibli-filmes-zduuwn',
    databaseURL: 'https://studio-ghibli-filmes-zduuwn-default-rtdb.firebaseio.com',
    storageBucket: 'studio-ghibli-filmes-zduuwn.appspot.com',
    iosBundleId: 'com.example.projetoloca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhNM938NYNJT99COnM2TlTNeD2P3ymoZw',
    appId: '1:937627284243:ios:5f0d53a5f4200ec1f260e6',
    messagingSenderId: '937627284243',
    projectId: 'studio-ghibli-filmes-zduuwn',
    databaseURL: 'https://studio-ghibli-filmes-zduuwn-default-rtdb.firebaseio.com',
    storageBucket: 'studio-ghibli-filmes-zduuwn.appspot.com',
    iosBundleId: 'com.example.projetoloca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXB-N0pwK44OHO7QFg0mvpNoiUnN98FGA',
    appId: '1:937627284243:web:301b5b42ec0a5b16f260e6',
    messagingSenderId: '937627284243',
    projectId: 'studio-ghibli-filmes-zduuwn',
    authDomain: 'studio-ghibli-filmes-zduuwn.firebaseapp.com',
    databaseURL: 'https://studio-ghibli-filmes-zduuwn-default-rtdb.firebaseio.com',
    storageBucket: 'studio-ghibli-filmes-zduuwn.appspot.com',
  );

}